### ISSUE TITLE
Checklist for release 2.1

### ISSUE THREAD

**Issue by AntonPetrov** [r2dt-bio/R2DT#150]
- [x] Make sure all tests pass
- [x] Generate precomputed library
- [x] Update version info in Readme and shared.py
- [x] Merge pull request
- [x] Check that Docker Hub updated the `latest` image
- [x] Publish GitHub release
- [x] Deploy the latest image on Job Dispatcher and test the API
- [ ] Publish blog post
- [x] Update Timeline Google Doc
- [x] Deploy new web app on rnacentral.org
- [x] Social outreach
    - [x] LinkedIn
    - [ ] Bluesky
    - [ ] X
- [ ] Create a checklist for the next release
